//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEyeGoglesOrderingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataGoglesEntities : DbContext
    {
        public DataGoglesEntities()
            : base("name=DataGoglesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<ContactTbl> ContactTbls { get; set; }
        public DbSet<OrderTB> OrderTBs { get; set; }
        public DbSet<TblUser> TblUsers { get; set; }
    }
}
